(define (make-monitored f)
  (let ((count 0))
       (lambda (m)
               (cond ((eq? m 'how-many-calls?) count)
                     ((eq? m 'reset-count) (begin (set! count 0)
                                                  count))
                     (else (begin (set! count (+ count 1)) (f m)))))))

(define s (make-monitored sqrt))
(s 100)
(s 49)
(s 'how-many-calls?)
