(load "base.scm")

(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (call-the-cops amount)
    (print "Calling the cops..."))
  (define (wrong-password amount)
    (print "Incorrect password"))
  (let ((count 0))
       (lambda (provided-password m)
         (if (not (eq? provided-password password))
             (begin (set! count (+ count 1))
                    (if (> count 7)
                        call-the-cops
                        wrong-password))
             (begin (set! count 0)
                    (cond ((eq? m 'withdraw) withdraw)
                          ((eq? m 'deposit) deposit)
                          (else (error "Unknown request: MAKE-ACCOUNT" m))))))))

(define acc (make-account 100 'secret-password))
(define (repeater f count)
  (if (> count 0)
      (begin (f) (repeater f (- count 1)))))

(repeater (lambda () ((acc 'some-other-password 'deposit) 50)) 7)
((acc 'secret-password 'deposit) 50)
(repeater (lambda () ((acc 'some-other-password 'deposit) 50)) 8)
