(load "deque.scm")

(define deque (make-deque))
(define deque1 (front-insert-deque! deque 'b))
(define deque2 (front-insert-deque! deque1 'a))
(display deque2)
(define deque3 (rear-insert-deque! deque2 'c))
(define deque4 (rear-insert-deque! deque3 'd))
(display deque4)

(define deque5 (front-delete-deque! deque4))
(display deque5)
(define deque6 (rear-delete-deque! deque5))
(display deque6)
(define deque7 (rear-delete-deque! deque6))
(display deque7)
(define deque8 (rear-delete-deque! deque7))
(display deque8)
(define deque9 (rear-delete-deque! deque8))
